import "./globals.css"
import { Providers } from "../contexts"
import MenuControl from "@/components/menu-control"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="da">
			<body>
				<Providers>
					<header>
						<MenuControl />
					</header>
					<main>
						{children}
					</main>
				</Providers>
			</body>
		</html>
	)
}
